apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-kubesysadm
  name: test-kubesysadm
  namespace: test-kubesysadm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-kubesysadm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-kubesysadm
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: Always
        name: busybox
        env:
          - name: ENV_SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-env
                key: userName
        volumeMounts:
        - name: secret-mount
          readOnly: true
          mountPath: /var/log/secretMount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: secret-mount
        secret:
          secretName: secret-mount

