# permissions for end users to edit cmmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubesysadm
  name: cmmonitor-editor-role
rules:
- apiGroups:
  - monitoring.sysadm.cn
  resources:
  - cmmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.sysadm.cn
  resources:
  - cmmonitors/status
  verbs:
  - get
