apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubesysadm
  name: kubesysadm-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get