---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.sysadm.cn
  resources:
  - cmmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.sysadm.cn
  resources:
  - cmmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.sysadm.cn
  resources:
  - cmmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.sysadm.cn
  resources:
  - podcleanrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.sysadm.cn
  resources:
  - podcleanrules/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.sysadm.cn
  resources:
  - podcleanrules/status
  verbs:
  - get
  - patch
  - update
