apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-kubesysadm
  name: test-kubesysadm
  namespace: test-kubesysadm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-kubesysadm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-kubesysadm
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: Always
        name: busybox
        env:
          - name: CONTAINER_ENV_USER 
            valueFrom: 
              configMapKeyRef:
                name: cm-env
                key: container_env_user
          - name: CONTAINER_ENV_PASSWD
            valueFrom:
              configMapKeyRef:
                name: cm-env
                key: container_env_passwd
        volumeMounts:
        - name: config
          mountPath: /var/log/config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: cm-mount

