apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kubesysadm
    control-plane: controller-manager
  name: kubesysadm-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager