name: Kubesysadm Controller Test

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  e2e_scheduling_basic:
    runs-on: ubuntu-22.04
    name: E2E about Kubesysadm Controller
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: Install musl
        run: |
          wget http://musl.libc.org/releases/musl-1.2.1.tar.gz
          tar -xf musl-1.2.1.tar.gz && cd musl-1.2.1
          ./configure
          make && sudo make install
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install dependences
        run: |
          GO111MODULE="on" go install sigs.k8s.io/kind@v0.23.0
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.29.0/bin/linux/amd64/kubectl && sudo install kubectl /usr/local/bin/kubectl
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run E2E Tests
        run: |
          make test-e2e-ksctl CC=/usr/local/musl/bin/musl-gcc